VAULT: update state tracker now accounts for multiple epochs passing when advancing state enqueued withdrawn VRT
jito-foundation/restaking pull request #124
Opened 2024-10-04 21:22 UTC by coachchucksol

To address H-02, Ive added the ability to shift the state of VRTs enqueued to withdraw - this mimics how the operators state is updated over multiple epochs. 

Tests have also been added to cover this edgecase.

2024-10-08 16:23 UTC, ebatsell commented on vault_program/src/close_update_state_tracker.rs
> +        .unwrap();
replace unwrap

2024-10-08 21:38 UTC, coachchucksol commented on vault_program/src/close_update_state_tracker.rs
> +        .unwrap();
Thanks!

2024-10-08 22:27 UTC, buffalu requested changes
can you add test for the bug this fixes?

2024-10-09 14:38 UTC, coachchucksol commented
The error code I've added is because we want to use checked_div. There is no way to make the epoch_length 0, so this can never happen. However, to add some clarity to it, I made a config helper function that will calculate the epoch given a slot. I have also added some - cant-be-zero checks in the integration tests for future proofing.

2024-10-09 17:16 UTC, buffalu approved these changes

2024-10-11 19:45 UTC, ebatsell commented on integration_tests/tests/vault/crank_vault_update_state_tracker.rs
> +    /// Test that the vrt withdrawal process if updating with normal crank operations
nit: update comment (same as above)

2024-10-11 19:48 UTC, ebatsell approved these changes

2024-10-11 20:39 UTC, coachchucksol commented on integration_tests/tests/vault/crank_vault_update_state_tracker.rs
> +    /// Test that the vrt withdrawal process if updating with normal crank operations
done

2024-10-14 17:32 UTC, merged