Rotate operator update indices
jito-foundation/restaking pull request #144
Opened 2024-10-22 23:38 UTC by ebatsell

Rotates the operator index we start on based on epoch % num_operators. Internally just tracks a counter from 0..num_operators and increments that, converting to the expected index number in check_and_update_index().

2024-10-23 00:02 UTC, coachchucksol reviewed
What happens if operators are added/removed mid update loop

2024-10-23 00:11 UTC, ebatsell commented on vault_core/src/vault_update_state_tracker.rs
> +    pub fn last_updated_index(&self, num_operators: u64) -> Result<u64, VaultError> {
operators can't get removed, but adding would be an issue I think

2024-10-23 15:30 UTC, ebatsell commented on vault_core/src/vault_update_state_tracker.rs
> +    pub fn last_updated_index(&self, num_operators: u64) -> Result<u64, VaultError> {
update: this is not an issue, operator adds are locked

2024-10-23 15:50 UTC, coachchucksol requested changes
Fix these issues

2024-10-23 19:15 UTC, coachchucksol approved these changes
lgtm

2024-10-23 19:16 UTC, coachchucksol commented on vault_core/src/vault_update_state_tracker.rs
> +
Note, this is done in the test `test_all_operators_updated` where the ncn epoch is 0 and n = 4. 0%4 = 0

2024-10-24 22:25 UTC, buffalu approved these changes

2024-10-24 22:29 UTC, buffalu approved these changes

2024-10-24 22:36 UTC, coachchucksol commented on integration_tests/tests/fixtures/vault_client.rs
> +        let ncn_epoch = slot / config.epoch_length();
It's in integration tests - do we still need check arithmetic?

2024-10-24 22:38 UTC, buffalu commented on integration_tests/tests/fixtures/vault_client.rs
> +        let ncn_epoch = slot / config.epoch_length();
oh u right u right

2024-10-24 22:38 UTC, buffalu commented on integration_tests/tests/fixtures/vault_client.rs
> +        let ncn_epoch = slot / config.epoch_length();
dont need to fix

2024-10-24 22:43 UTC, merged